# Generated by Django 3.1.3 on 2021-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20210617_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='mailchimp_list',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Mailchimp List'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mailchimp_template',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Mailchimp Template'),
        ),
    ]
